-- ============================================================
-- EPLMS SQL Schema (MySQL production version)
-- For H2 prototype, schema is auto-generated by Hibernate
-- ============================================================

CREATE DATABASE IF NOT EXISTS eplmsdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE eplmsdb;

CREATE TABLE managers (
    id       BIGINT AUTO_INCREMENT PRIMARY KEY,
    name     VARCHAR(100) NOT NULL,
    email    VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(20)  NOT NULL DEFAULT 'MANAGER'
);

CREATE TABLE hr_managers (
    id       BIGINT AUTO_INCREMENT PRIMARY KEY,
    name     VARCHAR(100) NOT NULL,
    email    VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(20)  NOT NULL DEFAULT 'HR_MANAGER'
);

CREATE TABLE employees (
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    email      VARCHAR(150) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    role       VARCHAR(20)  NOT NULL DEFAULT 'EMPLOYEE',
    manager_id BIGINT,
    CONSTRAINT fk_emp_manager FOREIGN KEY (manager_id) REFERENCES managers(id) ON DELETE SET NULL
);

CREATE TABLE leave_balances (
    id               BIGINT AUTO_INCREMENT PRIMARY KEY,
    employee_id      BIGINT NOT NULL UNIQUE,
    annual_leave     INT NOT NULL DEFAULT 21,
    sick_leave       INT NOT NULL DEFAULT 10,
    maternity_leave  INT NOT NULL DEFAULT 90,
    paternity_leave  INT NOT NULL DEFAULT 5,
    unpaid_leave     INT NOT NULL DEFAULT 30,
    CONSTRAINT fk_balance_emp FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);

CREATE TABLE leave_requests (
    id               BIGINT AUTO_INCREMENT PRIMARY KEY,
    employee_id      BIGINT       NOT NULL,
    leave_type       VARCHAR(20)  NOT NULL,
    start_date       DATE         NOT NULL,
    end_date         DATE         NOT NULL,
    total_days       INT          NOT NULL,
    reason           VARCHAR(500),
    status           VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    approver_comment VARCHAR(500),
    CONSTRAINT fk_leave_emp FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);

CREATE TABLE performance_goals (
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    employee_id BIGINT        NOT NULL,
    title       VARCHAR(200)  NOT NULL,
    description VARCHAR(1000),
    target_date DATE          NOT NULL,
    status      VARCHAR(20)   NOT NULL DEFAULT 'IN_PROGRESS',
    CONSTRAINT fk_goal_emp FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);

CREATE TABLE performance_reviews (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    employee_id     BIGINT        NOT NULL,
    reviewer_id     BIGINT,
    review_year     INT           NOT NULL,
    self_review     VARCHAR(2000),
    manager_review  VARCHAR(2000),
    self_rating     DOUBLE,
    manager_rating  DOUBLE,
    final_rating    DOUBLE,
    submitted_date  DATE          NOT NULL,
    status          VARCHAR(30)   NOT NULL DEFAULT 'SELF_REVIEW_PENDING',
    CONSTRAINT fk_review_emp      FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
    CONSTRAINT fk_review_manager  FOREIGN KEY (reviewer_id) REFERENCES managers(id) ON DELETE SET NULL,
    CONSTRAINT uq_review_year     UNIQUE (employee_id, review_year)
);

-- Indexes
CREATE INDEX idx_leave_employee  ON leave_requests(employee_id);
CREATE INDEX idx_leave_status    ON leave_requests(status);
CREATE INDEX idx_goal_employee   ON performance_goals(employee_id);
CREATE INDEX idx_review_employee ON performance_reviews(employee_id);
